# Site settings
title: Dominik Slomma
email: dominik.slomma@student.uts.edu.au
description: "Dominik Slomma is a robotics PhD student at UTS researching visual SLAM, surgical robotics, and perception-driven autonomy, with experience in UAV instruction, rescue robotics, real-time embedded systems, and automotive test engineering."
baseurl: ""
url: "https://dominikslomma.github.io"
lang: en
timezone: Australia/Sydney

sass:
  style: compressed

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Dominik Slomma<br/>
  Robotics Institute<br/>
  University of Technology Sydney

location: >
  University of Technology Sydney<br/>
  61 Broadway<br/>
  Sydney, Ultimo 2007

contact: >
  <a href="mailto:dominik.slomma@student.uts.edu.au" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Dominik Slomma via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: news
  - name: projects
  - name: publications
  - name: teaching
  # - name: talks
  # - name: research
  # - name: Code
  # - name: team
  # - name: teaching
  # - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll/scholar

scholar:
  last_name: Slomma
  first_name: [Dominik]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: /images/profilPic-800.jpg
      sitemap: true

exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - update_bootstrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
  - vendor
